
FROM nvcr.io/nvidia/rapidsai/base:24.10-cuda12.5-py3.10

USER root

WORKDIR /

RUN apt-get update && apt-get install git gcc g++ build-essential vim screen -y

RUN git clone https://github.com/NVIDIA/NeMo-Curator.git

RUN cd NeMo-Curator && pip install cython && pip install .

COPY compute_minhashes.py /NeMo-Curator/nemo_curator/scripts/fuzzy_deduplication/

COPY s3_reader.py NeMo-Curator/nemo_curator/scripts/fuzzy_deduplication/

RUN pip install s3fs